// scripts/build_differentials.js
// Run: OPENAI_API_KEY=... node scripts/build_differentials.js
// Output: src/data/differentials.js
// Requires: scripts/output/wikem_raw.json + scripts/output/pubmed_cases.json

require('dotenv').config();
const fetch = require('node-fetch');
const fs = require('fs');

const OPENAI_API_KEY = process.env.OPENAI_API_KEY;
if (!OPENAI_API_KEY) {
  console.error('Missing OPENAI_API_KEY in .env');
  process.exit(1);
}

const wikem = JSON.parse(fs.readFileSync('scripts/output/wikem_raw.json'));
const pubmed = JSON.parse(fs.readFileSync('scripts/output/pubmed_cases.json'));

function buildMissedDiagnosisIndex(pubmedRecords) {
  const index = {};
  const keywords = [
    'aortic dissection', 'subarachnoid', 'ectopic', 'testicular torsion',
    'epidural abscess', 'cauda equina', 'meningitis', 'pulmonary embolism',
    'stemi', 'appendicitis', 'intussusception', 'volvulus', 'carbon monoxide'
  ];

  for (const record of pubmedRecords) {
    const titleLower = (record.title || '').toLowerCase();
    for (const kw of keywords) {
      if (titleLower.includes(kw)) {
        index[kw] = (index[kw] || 0) + 1;
      }
    }
  }
  return index;
}

async function enrichComplaint(complaintData, missedIndex) {
  const prompt = `
You are building a medical education app. Enrich this emergency medicine differential diagnosis data for the chief complaint: "${complaintData.chiefComplaint}"

WIKEM SOURCE DATA:
All differentials listed: ${JSON.stringify(complaintData.differentials)}
WikEM must-not-miss section: ${JSON.stringify(complaintData.mustNotMiss)}
Management pearls: ${JSON.stringify(complaintData.managementPearls)}

PUBMED MISSED-DIAGNOSIS SIGNAL:
These diagnoses appear frequently in published missed-diagnosis case reports:
${JSON.stringify(missedIndex)}

Your task:
1. Categorize EVERY diagnosis from the WikEM list into mustNotMiss / common / rare
2. For must-not-miss diagnoses: add a 1-line teaching note explaining WHY it gets missed
3. Flag which must-not-miss diagnoses also appear in the PubMed missed-diagnosis signal
4. Identify the most common cognitive error for this chief complaint

Return ONLY valid JSON (no markdown, no preamble):
{
  "chiefComplaint": "${complaintData.chiefComplaint}",
  "wikemUrl": "${complaintData.wikemUrl}",
  "mustNotMiss": [
    {
      "diagnosis": "<name>",
      "whyMissed": "<1-sentence explanation of why clinicians miss this>",
      "cognitiveError": "anchoring | availability | premature_closure | framing | omission",
      "appearsInCaseReports": true | false
    }
  ],
  "common": ["<diagnosis>", ...],
  "rare": ["<diagnosis>", ...],
  "expertTip": "<1-2 sentence attending-level pearl for approaching this chief complaint>",
  "dominantCognitiveError": "anchoring | availability | premature_closure | framing | omission"
}
`;

  const response = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${OPENAI_API_KEY}`
    },
    body: JSON.stringify({
      model: 'gpt-4o',
      max_tokens: 1500,
      temperature: 0.3,
      messages: [
        { role: 'system', content: 'You are a board-certified emergency medicine attending with expertise in diagnostic error. Return only valid JSON.' },
        { role: 'user', content: prompt }
      ]
    })
  });

  const data = await response.json();
  if (data.error) {
    throw new Error(data.error.message);
  }
  const text = data.choices[0].message.content.replace(/```json|```/g, '').trim();
  return JSON.parse(text);
}

async function main() {
  fs.mkdirSync('src/data', { recursive: true });
  const missedIndex = buildMissedDiagnosisIndex(pubmed);
  console.log('Missed diagnosis index:', missedIndex);

  const enriched = {};

  for (const [key, complaintData] of Object.entries(wikem)) {
    if (complaintData.differentials.length === 0) {
      console.log(`Skipping ${complaintData.chiefComplaint} (no differentials found)`);
      continue;
    }
    console.log(`Enriching: ${complaintData.chiefComplaint}...`);
    try {
      enriched[key] = await enrichComplaint(complaintData, missedIndex);
      console.log(`  OK: ${enriched[key].mustNotMiss.length} must-not-miss, ${enriched[key].common.length} common`);
    } catch (e) {
      console.error(`  FAIL: ${e.message}`);
    }
    await new Promise(r => setTimeout(r, 1000));
  }

  const output = `// AUTO-GENERATED by scripts/build_differentials.js
// Sources: WikEM (CC BY-NC-SA) + PubMed E-utilities
// Regenerate: node scripts/build_differentials.js

export const differentials = ${JSON.stringify(enriched, null, 2)};

export const CHIEF_COMPLAINTS = Object.keys(differentials).map(k => differentials[k].chiefComplaint);
`;

  fs.writeFileSync('src/data/differentials.js', output);
  console.log(`\nWrote ${Object.keys(enriched).length} complaints -> src/data/differentials.js`);
}

main().catch(console.error);
